import { ThemeProvider } from "@/components/ThemeProvider"
import { siteConfig } from "@/config/site"
import { ClerkProvider } from "@clerk/nextjs"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html suppressHydrationWarning>
    <body
      className=
        "min-h-screen bg-background font-sans antialiased"
    >
      <ThemeProvider
        attribute="class" 
        defaultTheme={siteConfig.nextThemeColor}
        enableSystem
      >
        <ClerkProvider>{children}</ClerkProvider>
      </ThemeProvider>
    </body>
    </html>
  )
}
